name: Web Testing - Test No1

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --B package --file pom.xml
  Chrome:
    name: setup-chromedriver
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@v1
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: '99.0.4844.51'
      - run: chromedriver --url-base=/wd/hub &
  Test:
    name: Testing Web Automation
    needs: Chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Web Test
        run: mvn clean verify